### PR TITLE
Changed deformation gradient field names

### PR DESCRIPTION
**Pull request by andrisfreimanis**
In bond associated material base class, deformation gradient and deformation gradient dot fields were named "Velocity_Gradient_...". This edit changes their names to "Deformation_Gradient_...".

All tests passed after the change.

### CODE REVIEW

**Comment by diehlpk** [comment]
@andrisfreimanis can you please elaborate why you changed the name?

**Comment by andrisfreimanis** [comment]
Yes, I should have included that.

The fields have the wrong names (string describing the field) associated with them. The variables names (m_deformationGradientXFieldId, m_deformationGradientDotXFieldId etc.) properly indicate that the deformation gradient (F) and its time derivative (F dot)  field IDs will be stored in them. However, the name (string associated with them) says "Velocity_Gradient_X" and "Velocity_Gradient_Dot_X", which is a different gradient.

It will cause confusion in three cases. (1) In the Output section of a .yaml file, when a user wants to save deformation gradient data they have to ask for velocity gradient, or they will get an error saying that deformation gradient data are not available. (2) Conversely, they might ask for the velocity gradient, to be stored, but will get the deformation gradient. (3) In a derived class, the developer must ask the data manager for the velocity gradient, when they need the deformation gradient field id.

It has not caused problems yet, because the publicly available materials use the rate of deformation, but it can cause problems later.

The bond level data fields have the proper names e.g. m_bondLevelDeformationGradientInvXXFieldId and "Deformation_Gradient_Inv_XX".

**Comment by oldninja** [comment]
I can see case (1) definitely happening to me.

**Comment by diehlpk** [comment]
Thanks for the explanation. Sounds good.

**Review by diehlpk — APPROVED** [review]
LGTM!

**Comment by diehlpk** [comment]
@andrisfreimanis I would assume that this affects the teste or?

I have not seen any changes in the tests?

**Comment by andrisfreimanis** [comment]
This affects no current test. The problem was contained in the BondAssociatedCorrespondenceMaterial class, because all public bond associated material models use the rate of deformation not the deformation gradient to compute Cauchy stress. To my knowledge there are no tests for the BondAssociatedCorrsepondenceMaterial class. The existing tests would only check derived material classes, which worked and still work fine.

**Comment by diehlpk** [comment]
Thanks for checking. Once the CI is up again, I will merge the pull request.

**Pull request merged**
