### PR TITLE
Clean formate of source files

### PR DESCRIPTION
**Pull request by jritta**
Formatting of source files cleaned for better readability.
In preparation for full update to python 3 and bug fixes.

### CODE REVIEW

**Comment by diehlpk** [comment]
@jritta Could you please rebase the current master and I will review the pull request again.

**Comment by jritta** [comment]
@diehlpk I rebased the current master and on top the clean_format branch as well. Thus, all merge conflicts should be already be resolved.

**Review by diehlpk — APPROVED** [review]
LGTM!

**Comment by diehlpk** [comment]
@jritta We are setting up some continuous integration and once your pull request passes there, we will merge it to master.

**Comment by jritta** [comment]
@diehlpk perfect, sounds good to me!

**Pull request merged**
