### PR TITLE
Fix issue #129

### PR DESCRIPTION
**Pull request by jritta**
This pull request fixes issue #129. 
The variable `currentTime` is correctly initialized based on the *InitialTime* of the first solver in the input deck.
When the *Intital Time* in the input deck of a following run does not match the *currentTime* of the last restart folder the simulation aborts with an exception of incompatible times.

### CODE REVIEW

**Comment by jritta** [comment]
Is based on changes of #133

**Review by diehlpk — APPROVED** [review]
LGTM!

**Comment by diehlpk** [comment]
@jritta This seems to be a duplicate of #61. Can you please confirm? So I would merge yours and close the older one.

**Comment by jritta** [comment]
@diehlpk Yes I can confirm, but it is not a hard coded correct initialization. The solution in #135 works also for an solver `Initial Time != 0.0` and I also tested it for a series of solvers.

**Pull request merged**
