### PR TITLE
Made all scripts Python3 compatible

### PR DESCRIPTION
**Pull request by jritta**
All Python scripts of Peridigm are updated to work with Python3. The scripts were tested on a Fedora 32 system for both Python 3.8.6 and Python 2.7.18

This pull request uses changes made in #133

### CODE REVIEW

**Review by diehlpk — APPROVED** [review]
LGTM!

**Comment by diehlpk** [comment]
Same here once we have the continuous integration, we will merge this pull request.

**Comment by jritta** [comment]
Ok no problem! @diehlpk can anyone in some way help you set up the CI?

**Comment by diehlpk** [comment]
We are close to do that, however, there is one compiler issues, I will resolve soon.

**Comment by diehlpk** [comment]
@jritta We have the CI setup, however, there are some issues with the Python code reported by Codacy. Could you please have a look?

**Comment by jritta** [comment]
@diehlpk thanks for setting up the CI!
I checked the result by Codacy, it is all related to parts of the code which I did not touch. The original version of [mirror.py](../blob/45eac575fc7ec05f524c5196a3de0e752583fe3e/scripts/mirror.py) and [xmlripper.py](../blob/45eac575fc7ec05f524c5196a3de0e752583fe3e/scripts/xmlripper.py) should give the same result.

Should I fix them that they pass the static code analysis?

**Comment by diehlpk** [comment]
> Should I fix them that they pass the static code analysis?

Yes, that woukd be amazing,

**Comment by jritta** [comment]
@diehlpk I worked on the files. The static code analysis within github still reveals some issues. I can fix some of them (docstring stuff), but others would require much more changes (e.g. functions that are too complex). I do not know if this is really productive if we try to get all of them fixed. What do you think about it?

**Comment by diehlpk** [comment]
@jritta that is fine. I will have a look later and will merge your pull request. Thanks again.

**Pull request merged**
