### PR TITLE
Bond-Associated Lagrangian Correspondence PD added

### PR DESCRIPTION
**Pull request by masoudbehzadinasab**
A new material class is added based on the Lagrangian BA-PD.
Elastic, Elastic-Plastic, and Isotropic-Hardening materials are added
as a sub-class. The high-order implicit gradient functions are
incorporated to compute the deformation gradient, which is then used to
evaluate the Piola-Kirchhoff stress tensor. A new test is also included
to feature the input type for this new class of materials.

### CODE REVIEW

**Comment by diehlpk** [comment]
@masoudbehzadinasab Could you please have a look at the Codacy Static Code Analysis?

**Comment by masoudbehzadinasab** [comment]
> @masoudbehzadinasab Could you please have a look at the Codacy Static Code Analysis?

Sure. I just signed up for that. Do you just want Codacy to do the automatic check when I submit a pull request? Or anything in particular wrong with this commit? I see that Codacy Static Code Analysis finds 1000+ issues with the code (looks like mostly are not actual issues, and they pretty much all go back to the previous commits).

**Comment by masoudbehzadinasab** [comment]
> > @masoudbehzadinasab Could you please have a look at the Codacy Static Code Analysis?
> 
> Sure. I just signed up for that. Do you just want Codacy to do the automatic check when I submit a pull request? Or anything in particular wrong with this commit? I see that Codacy Static Code Analysis finds 1000+ issues with the code (looks like mostly are not actual issues, and they pretty much all go back to the previous commits).

@diehlpk Actually Codacy helped me finding out a few things to fix. I'll close this pull and resubmit the modified version. Thanks for the tip!

**Comment by diehlpk** [comment]
@masoudbehzadinasab Yes, it codacy will check every pull request. it is sufficient, if you look into the files you changed.

**Pull request closed without merging**
