### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by jritta**
This implements a full Python 3 compatibility of the existing python scripts. It was tested for Python 3.8.6 and Python 2.7.18 on a Fedora 32 system.

### CODE REVIEW

**Comment by jritta** [comment]
It is based on changes of #133

**Comment by diehlpk** [comment]
@jritta I think this was already fixed in #131, if, so I will close this pull request.

**Comment by jritta** [comment]
@diehlpk in #131 only the Python script [mirror.py](https://github.com/peridigm/peridigm/blob/master/scripts/mirror.py) was updated. In my pull request I went through all Python files of Peridigm and updated them to work with Python3.8 and Python2.7. I also made sure that they use the correct exodus wrapper, i.e. exodus2.py or exodus3.py, respectively.

**Comment by diehlpk** [comment]
Ok, please do a new pull request and mention this there.

**Comment by jritta** [comment]
@diehlpk sorry for the imprecise pull request title. I created a new one, see #137

**Pull request closed without merging**
